controllers:
  resource: ../../src/Controller/
  type: annotation

kernel:
  resource: ../../src/Kernel.php
  type: annotation

api_weather:
  resource: ../../src/Controller/Api/Weather
  type: annotation
  prefix: '/api/weather'
